basePath: /api/v1
definitions:
  swagger.StatusBadRequest:
    properties:
      code:
        example: BAD_REQUEST
        type: string
      message:
        example: Bad request
        type: string
    type: object
  swagger.StatusForbidden:
    properties:
      code:
        example: FORBIDDEN
        type: string
      message:
        example: You don't have permission to access this resource
        type: string
    type: object
  swagger.StatusInternalError:
    properties:
      code:
        example: INTERNAL_ERROR
        type: string
      message:
        example: Internal server error
        type: string
    type: object
  swagger.UserByIDResponseSwagger:
    properties:
      user:
        $ref: '#/definitions/swagger.UserSwagger'
    type: object
  swagger.UserSwagger:
    properties:
      created_at:
        example: "2021-01-01T00:00:00Z"
        type: string
      email:
        example: test@test.com
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      updated_at:
        example: "2021-01-01T00:00:00Z"
        type: string
      username:
        example: JohnDoe
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@gmail.com
    name: API Support
    url: https://example.com/
  description: GO API documentation
  title: Go API
  version: "1.0"
paths:
  /users/{user_id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        format: uuid
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Get user by ID
          schema:
            $ref: '#/definitions/swagger.UserByIDResponseSwagger'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.StatusBadRequest'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/swagger.StatusForbidden'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.StatusInternalError'
      summary: Get user by ID
      tags:
      - User
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
